import React, { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";
import Layout from "../components/Layout";
import PageHeader from "../components/PageHeader";

export default function InventoryPage() {
  const [items, setItems] = useState([]); const [categories, setCategories] = useState([]); const [products, setProducts] = useState([]); const [search, setSearch] = useState(""); const [mode, setMode] = useState(""); const [error, setError] = useState("");
  const load = () => Promise.all([api("/items"), api("/categories"), api("/products")]).then(([a, b, c]) => { setItems(a.data); setCategories(b.data); setProducts(c.data); }).catch((e) => setError(e.message));
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => items.filter((item) => item.name.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const createCategory = async (event) => { event.preventDefault(); const name = new FormData(event.currentTarget).get("name"); try { await api("/categories", { method: "POST", body: JSON.stringify({ name }) }); event.currentTarget.reset(); setMode(""); load(); } catch (e) { setError(e.message); } };
  const createItem = async (event) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); try { await api("/items", { method: "POST", body: JSON.stringify({ ...form, price: Number(form.price), stock: Number(form.stock) }) }); event.currentTarget.reset(); setMode(""); load(); } catch (e) { setError(e.message); } };
  return <Layout><PageHeader title="Inventory" subtitle="Keep products and stock quantities accurate." action={<div className="button-group"><button className="secondary" onClick={() => setMode("category")}>+ Category</button><button className="primary" onClick={() => setMode("item")}>+ Add item</button></div>} />{error && <div className="notice error">{error}</div>}
    {mode && <div className="modal-backdrop"><div className="modal"><button className="close" onClick={() => setMode("")}>×</button><h2>{mode === "category" ? "Add category" : "Add inventory item"}</h2>{mode === "category" ? <form onSubmit={createCategory}><label>Category name<input name="name" required placeholder="e.g. Staples" /></label><button className="primary full">Save category</button></form> : <form onSubmit={createItem}><label>Item name<input name="name" required placeholder="e.g. Aashirvaad Atta 5 kg" /></label><div className="two-col"><label>Price<input name="price" type="number" min="0" step="0.01" required /></label><label>Opening stock<input name="stock" type="number" min="0" step="0.001" required /></label></div><label>Unit<select name="unitType" defaultValue="PIECE">{["KG", "GRAM", "LITRE", "ML", "PIECE", "DOZEN", "PACKET", "BOX", "BOTTLE", "OTHER"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Product<select name="productId" required defaultValue=""><option value="" disabled>Select product</option>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Category<select name="categoryId" required defaultValue=""><option value="" disabled>Select category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="primary full">Save item</button></form>}</div></div>}
    <section className="panel table-panel"><div className="table-toolbar"><div><h3>All inventory</h3><p>{items.length} items in catalogue</p></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search items…" /></div><div className="responsive-table"><table><thead><tr><th>Item</th><th>Category</th><th>Price</th><th>Available stock</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.product?.name}</small></td><td>{item.category?.name}</td><td>₹{Number(item.price).toFixed(2)}</td><td><span className={Number(item.stock) <= 5 ? "stock-low badge" : "badge"}>{item.stock} {item.unitType}</span></td></tr>)}{!visible.length && <tr><td colSpan="4" className="empty">No items found.</td></tr>}</tbody></table></div></section></Layout>;
}
